### ISSUE TITLE
国家地区旗 emoji 被 PR 错误修改

### ISSUE THREAD

**Issue by jakeslee** [tindy2013/subconverter#275]
你好大佬，今天更新订阅发现台湾节点的 emoji 从中国国旗被修改为 TW 区旗导致无法正常显示。

经查看提交记录，发现是最近的合并把 emoji 变更了：

Modify Emoji matching rules #273 

https://github.com/tindy2013/subconverter/blob/c0d079202a25d5cc18e6b9a1621f0d0ab7c47f7e/base/snippets/emoji.txt#L37-L40

**Comment by tindy2013** [comment]
Fixed in d46aa6133e80c26a14054bc4f1dbba35f431c265

**Comment by wsxy162** [comment]
The issue is from the client (phone OS), change this flag emoji to another one doesn't fix the issue. If the client can't display this flag, just let it, no flag suits their policy and needs. Please revert it back.

**Comment by gang4399** [comment]
@wsxy162 Which one?
